language: python

python:
#  - "2.6"
#  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "3.5-dev"  # 3.5 development branch
  - "3.6"
#  - "3.6-dev"  # 3.6 development branch
#  - "3.7-dev"  # 3.7 development branch

cache: pip

# command to install dependencies
install:
  - 'pip install -r requirements-dev.txt'
  - 'pip install -r requirements.txt'
  - 'pip install coveralls'

script: 
  -  'python -m pytest --junitxml ./reports/results.xml --cov-config .coveragerc --cov=src .'

after_success:
  - coveralls

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "6kcJSnV5AmaqmB6Y2x3PBkmskrg0TuuTQ+IusSZR53J5e6qjbMgSyukks9h9xUBpGOlFlpTgLjrwzdaEkZUhSK6L+SquzjLRUcr05RndIBof2hxeXvvTcWeT1h5uEAYwnuGtBNUJObLPzS9tqQueKUuoqM4Ebi5Xq173TlUKBDmAfRdZI2MaNby8JirrU6iB+tLMhFWF8ymPW/ZMBi1+hBX1VcAyPk61dz1cTkWi9YqXyNe+OrsjM5n9bLE3bBc7qfgrQg1ZUopBIlApANc3CZOS91Bmbgo/dEv4waVJvs0Ugr+1ViX1ECroE/eHkRfu7UrsEEzUkdB+Nv/BSzV9aIpP9jWYx1UlqRbvfnp8PevmnYpDYZv95H7vktXAc+Y1E9MkvIboDXeb6TRlXY9V/qYHJWxDnKcmQnPwV6mVGWO3iH2C3jMeXLhwgfUaTWIp+BEARXl4mtHniJ4z1ZmWdQa0/Ty+HIOz1fAN0MNbLGRt5Gjj/c12DKbYvMc4SqL5Gx4Rd5UVgmp+anXIYmMiw3OFskI49eNopBWP9LDl6VaTuYdY8d/a+xG7+j9hZZo9Udmj1ZkPWuyV4tvOZ91jFcGKZZ84HOyUd7vv+/g0IsOTtv7tAzBrmkxS5E4Rup1MJrv8RT//WtoTWPbQNe+cqwf8UdisSgX1rcA75ugu410="
  skip_existing: true
  distributions: "sdist bdist_wheel"
  on:
    tags: true
